#!/usr/bin/env python2

import argparse
import os.path
import pickle
import yaml

parser = argparse.ArgumentParser(description='Convert yaml to pickle.')
parser.add_argument('yaml', help='YAML file')

args = parser.parse_args()
input_filename = args.yaml
output_filename = os.path.splitext(args.yaml)[0]+'.pickle'

pickle.dump(yaml.load(open(input_filename, 'r')), open(output_filename, 'w'), pickle.HIGHEST_PROTOCOL)
